FROM node:25.8-alpine3.22
WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma
COPY fix-prisma-imports.js ./

RUN npm ci --legacy-peer-deps
RUN npx prisma generate && node fix-prisma-imports.js

COPY scripts ./scripts

ENTRYPOINT ["npx", "tsx"]
