import { PrismaClient } from "@prisma/client";
import { exerciseAchievements } from "./seedExerciseAchievements";

const prisma = new PrismaClient();

const achievements = [
  // First Steps
  {
    key: "FIRST_TUTORIAL",
    title: "Welcome Explorer 📚",
    description: "Start your first tutorial",
    icon: "📚",
    category: "learning",
    rarity: "COMMON",
    points: 5,
    requirementType: "tutorial_start",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "FIRST_QUIZ",
    title: "First Steps 🎯",
    description: "Complete your first quiz",
    icon: "🎯",
    category: "learning",
    rarity: "COMMON",
    points: 10,
    requirementType: "quiz_count",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "FIRST_CHALLENGE",
    title: "Code Newbie 💻",
    description: "Solve your first coding challenge",
    icon: "💻",
    category: "challenge",
    rarity: "COMMON",
    points: 15,
    requirementType: "challenge_count",
    requirementValue: 1,
    isHidden: false,
  },

  // Learning Achievements
  {
    key: "QUIZ_MASTER_10",
    title: "Quiz Explorer 🧠",
    description: "Complete 10 quizzes",
    icon: "🧠",
    category: "learning",
    rarity: "RARE",
    points: 50,
    requirementType: "quiz_count",
    requirementValue: 10,
    isHidden: false,
  },
  {
    key: "QUIZ_MASTER_25",
    title: "Quiz Master 👑",
    description: "Complete 25 quizzes",
    icon: "👑",
    category: "learning",
    rarity: "EPIC",
    points: 100,
    requirementType: "quiz_count",
    requirementValue: 25,
    isHidden: false,
  },
  {
    key: "PERFECT_SCORE",
    title: "Perfectionist ⭐",
    description: "Score 100% on a quiz",
    icon: "⭐",
    category: "learning",
    rarity: "RARE",
    points: 25,
    requirementType: "perfect_score",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "SPEED_DEMON",
    title: "Speed Demon ⚡",
    description: "Complete a quiz in under 30 seconds",
    icon: "⚡",
    category: "speed",
    rarity: "EPIC",
    points: 30,
    requirementType: "quiz_time",
    requirementValue: 30,
    isHidden: false,
  },

  // Challenge Achievements
  {
    key: "CHALLENGE_MASTER_5",
    title: "Code Solver 🔧",
    description: "Solve 5 coding challenges",
    icon: "🔧",
    category: "challenge",
    rarity: "RARE",
    points: 40,
    requirementType: "challenge_count",
    requirementValue: 5,
    isHidden: false,
  },
  {
    key: "CHALLENGE_MASTER_15",
    title: "Algorithm Expert 🚀",
    description: "Solve 15 coding challenges",
    icon: "🚀",
    category: "challenge",
    rarity: "EPIC",
    points: 75,
    requirementType: "challenge_count",
    requirementValue: 15,
    isHidden: false,
  },

  // Points Achievements
  {
    key: "POINTS_100",
    title: "Point Collector 💰",
    description: "Earn 100 total points",
    icon: "💰",
    category: "points",
    rarity: "COMMON",
    points: 25,
    requirementType: "total_points",
    requirementValue: 100,
    isHidden: false,
  },
  {
    key: "POINTS_500",
    title: "Point Master �",
    description: "Earn 500 total points",
    icon: "💎",
    category: "points",
    rarity: "RARE",
    points: 50,
    requirementType: "total_points",
    requirementValue: 500,
    isHidden: false,
  },
  {
    key: "POINTS_1000",
    title: "Point Legend 🏆",
    description: "Earn 1000 total points",
    icon: "🏆",
    category: "points",
    rarity: "LEGENDARY",
    points: 100,
    requirementType: "total_points",
    requirementValue: 1000,
    isHidden: false,
  },

  // Mood-based Achievements
  {
    key: "CHILL_LEARNER",
    title: "Chill Vibes 😎",
    description: "Complete 10 quizzes in Chill mode",
    icon: "😎",
    category: "mood",
    rarity: "RARE",
    points: 30,
    requirementType: "chill_quizzes",
    requirementValue: 10,
    isHidden: false,
  },
  {
    key: "FOCUSED_LEARNER",
    title: "Laser Focus 🎯",
    description: "Complete 10 quizzes in Focused mode",
    icon: "🎯",
    category: "mood",
    rarity: "RARE",
    points: 30,
    requirementType: "focused_quizzes",
    requirementValue: 10,
    isHidden: false,
  },
  {
    key: "CRACKED_LEARNER",
    title: "Absolutely Cracked 🔥",
    description: "Complete 10 quizzes in Cracked mode",
    icon: "🔥",
    category: "mood",
    rarity: "EPIC",
    points: 50,
    requirementType: "cracked_quizzes",
    requirementValue: 10,
    isHidden: false,
  },
  {
    key: "challenge_solver",
    title: "Problem Solver 🔧",
    description: "Solve 25 coding challenges",
    icon: "🔧",
    category: "challenge",
    rarity: "RARE",
    points: 75,
    requirementType: "challenge_count",
    requirementValue: 25,
    isHidden: false,
  },
  {
    key: "coding_genius",
    title: "Coding Genius 🚀",
    description: "Solve 100 coding challenges",
    icon: "🚀",
    category: "challenge",
    rarity: "LEGENDARY",
    points: 300,
    requirementType: "challenge_count",
    requirementValue: 100,
    isHidden: false,
  },

  // Speed Achievements
  {
    key: "speed_demon",
    title: "Speed Demon ⚡",
    description: "Complete a quiz in under 2 minutes",
    icon: "⚡",
    category: "speed",
    rarity: "EPIC",
    points: 100,
    requirementType: "quiz_speed",
    requirementValue: 120, // 2 minutes in seconds
    isHidden: false,
  },
  {
    key: "lightning_fast",
    title: "Lightning Fast 🌩️",
    description: "Complete a challenge in under 5 minutes",
    icon: "🌩️",
    category: "speed",
    rarity: "EPIC",
    points: 150,
    requirementType: "challenge_speed",
    requirementValue: 300, // 5 minutes in seconds
    isHidden: false,
  },

  // Streak Achievements
  {
    key: "consistent_learner",
    title: "Consistent Learner 📅",
    description: "Learn for 3 days in a row",
    icon: "📅",
    category: "streak",
    rarity: "COMMON",
    points: 25,
    requirementType: "daily_streak",
    requirementValue: 3,
    isHidden: false,
  },
  {
    key: "dedicated_student",
    title: "Dedicated Student 📚",
    description: "Learn for 7 days in a row",
    icon: "📚",
    category: "streak",
    rarity: "RARE",
    points: 50,
    requirementType: "daily_streak",
    requirementValue: 7,
    isHidden: false,
  },
  {
    key: "learning_machine",
    title: "Learning Machine 🤖",
    description: "Learn for 30 days in a row",
    icon: "🤖",
    category: "streak",
    rarity: "LEGENDARY",
    points: 500,
    requirementType: "daily_streak",
    requirementValue: 30,
    isHidden: false,
  },

  // Mood-specific Achievements
  {
    key: "chill_master",
    title: "Chill Master 😌",
    description: "Complete 20 activities in chill mode",
    icon: "😌",
    category: "mood",
    rarity: "RARE",
    points: 60,
    requirementType: "mood_activities",
    requirementValue: 20,
    isHidden: false,
  },
  {
    key: "rush_warrior",
    title: "Rush Warrior 🔥",
    description: "Complete 20 activities in rush mode",
    icon: "🔥",
    category: "mood",
    rarity: "RARE",
    points: 60,
    requirementType: "mood_activities",
    requirementValue: 20,
    isHidden: false,
  },
  {
    key: "grind_champion",
    title: "Grind Champion 💪",
    description: "Complete 20 activities in grind mode",
    icon: "💪",
    category: "mood",
    rarity: "RARE",
    points: 60,
    requirementType: "mood_activities",
    requirementValue: 20,
    isHidden: false,
  },

  // Social Achievements
  {
    key: "social_butterfly",
    title: "Social Butterfly 🦋",
    description: "Add your first friend",
    icon: "🦋",
    category: "social",
    rarity: "COMMON",
    points: 20,
    requirementType: "friend_count",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "popular_learner",
    title: "Popular Learner 🌟",
    description: "Have 10 friends",
    icon: "🌟",
    category: "social",
    rarity: "RARE",
    points: 100,
    requirementType: "friend_count",
    requirementValue: 10,
    isHidden: false,
  },

  // Perfect Score Achievements
  {
    key: "perfectionist",
    title: "Perfectionist ✨",
    description: "Get 100% on a quiz",
    icon: "✨",
    category: "performance",
    rarity: "RARE",
    points: 75,
    requirementType: "perfect_quiz",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "flawless_coder",
    title: "Flawless Coder 💎",
    description: "Solve a challenge on first try",
    icon: "💎",
    category: "performance",
    rarity: "EPIC",
    points: 125,
    requirementType: "first_try_challenge",
    requirementValue: 1,
    isHidden: false,
  },

  // Hidden/Special Achievements
  {
    key: "easter_egg_hunter",
    title: "Easter Egg Hunter 🥚",
    description: "Found a hidden easter egg",
    icon: "🥚",
    category: "special",
    rarity: "EPIC",
    points: 200,
    requirementType: "easter_egg",
    requirementValue: 1,
    isHidden: true,
  },
  {
    key: "night_owl",
    title: "Night Owl 🦉",
    description: "Complete activities between 11 PM and 5 AM",
    icon: "🦉",
    category: "special",
    rarity: "RARE",
    points: 50,
    requirementType: "night_activity",
    requirementValue: 5,
    isHidden: true,
  },

  // Import exercise achievements from separate file for easier management
  ...exerciseAchievements,
];

async function seedAchievements() {
  console.log("🏆 Seeding achievements...");

  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { key: achievement.key },
      update: achievement,
      create: achievement,
    });
    console.log(`✅ Created achievement: ${achievement.title}`);
  }

  console.log(`🎉 Successfully seeded ${achievements.length} achievements!`);
}

seedAchievements()
  .catch((e) => {
    console.error("❌ Error seeding achievements:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
