/**
 * Exercise Achievement Definitions
 * Separate file for easier management and updates
 */

export const exerciseAchievements = [
  // First Exercise
  {
    key: "FIRST_EXERCISE",
    title: "Hands-On Learner 🛠️",
    description: "Complete your first exercise",
    icon: "🛠️",
    category: "exercise",
    rarity: "COMMON",
    points: 15,
    requirementType: "exercise_count",
    requirementValue: 1,
    isHidden: false,
  },

  // Quality & Performance Achievements
  {
    key: "EXERCISE_PERFECTIONIST",
    title: "Perfect First Try 🎯",
    description: "Pass all tests on your first attempt",
    icon: "🎯",
    category: "exercise",
    rarity: "EPIC",
    points: 100,
    requirementType: "first_try_exercise",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "NO_HINTS_MASTER",
    title: "Independent Thinker 🧠",
    description: "Complete 5 exercises without using hints",
    icon: "🧠",
    category: "exercise",
    rarity: "RARE",
    points: 75,
    requirementType: "no_hints_exercises",
    requirementValue: 5,
    isHidden: false,
  },
  {
    key: "EXERCISE_SPEEDSTER",
    title: "Speed Coder ⚡",
    description: "Complete an exercise in under half the estimated time",
    icon: "⚡",
    category: "exercise",
    rarity: "EPIC",
    points: 120,
    requirementType: "exercise_speed",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "CLEAN_CODE_CHAMPION",
    title: "Clean Code Champion ✨",
    description: "Pass all tests with zero errors in 3 exercises",
    icon: "✨",
    category: "exercise",
    rarity: "RARE",
    points: 80,
    requirementType: "clean_code_exercises",
    requirementValue: 3,
    isHidden: false,
  },

  // Skill-Based Achievements
  {
    key: "HTML_CSS_MASTER",
    title: "HTML & CSS Master 🎨",
    description: "Complete all HTML & CSS exercises",
    icon: "🎨",
    category: "exercise",
    rarity: "EPIC",
    points: 150,
    requirementType: "category_complete",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "JAVASCRIPT_NINJA",
    title: "JavaScript Ninja 🥷",
    description: "Complete all JavaScript exercises",
    icon: "🥷",
    category: "exercise",
    rarity: "EPIC",
    points: 150,
    requirementType: "category_complete",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "DOM_WIZARD",
    title: "DOM Wizard 🧙",
    description: "Complete all DOM manipulation exercises",
    icon: "🧙",
    category: "exercise",
    rarity: "RARE",
    points: 100,
    requirementType: "category_complete",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "FULL_STACK_BUILDER",
    title: "Full Stack Builder 🏗️",
    description: "Complete exercises from 3 different categories",
    icon: "🏗️",
    category: "exercise",
    rarity: "RARE",
    points: 90,
    requirementType: "exercise_categories",
    requirementValue: 3,
    isHidden: false,
  },
  {
    key: "DIFFICULTY_CLIMBER",
    title: "Difficulty Climber 🧗",
    description: "Complete beginner, intermediate, and advanced exercises",
    icon: "🧗",
    category: "exercise",
    rarity: "EPIC",
    points: 125,
    requirementType: "difficulty_progression",
    requirementValue: 3,
    isHidden: false,
  },

  // Learning & Progress Achievements
  {
    key: "PROBLEM_SOLVER",
    title: "Problem Solver 🔍",
    description: "Succeed after failing an exercise once",
    icon: "🔍",
    category: "exercise",
    rarity: "COMMON",
    points: 40,
    requirementType: "problem_solver",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "PERSISTENT_LEARNER",
    title: "Persistent Learner 💪",
    description: "Complete an exercise after 3 or more attempts",
    icon: "💪",
    category: "exercise",
    rarity: "RARE",
    points: 60,
    requirementType: "persistent_exercise",
    requirementValue: 1,
    isHidden: false,
  },

  // Specific Exercise Achievements
  {
    key: "CALCULATOR_MASTER",
    title: "Calculator Master 🔢",
    description: "Complete the Calculator exercise",
    icon: "🔢",
    category: "exercise",
    rarity: "COMMON",
    points: 30,
    requirementType: "specific_exercise",
    requirementValue: 1,
    isHidden: false,
  },
  {
    key: "FORM_VALIDATOR_PRO",
    title: "Form Validator Pro ✅",
    description: "Complete the Form Validation exercise",
    icon: "✅",
    category: "exercise",
    rarity: "COMMON",
    points: 30,
    requirementType: "specific_exercise",
    requirementValue: 1,
    isHidden: false,
  },

  // Milestone Achievements
  {
    key: "EXERCISE_MARATHON",
    title: "Exercise Marathon 🏃",
    description: "Complete 10 exercises in a single session",
    icon: "🏃",
    category: "exercise",
    rarity: "EPIC",
    points: 200,
    requirementType: "exercise_session",
    requirementValue: 10,
    isHidden: false,
  },
  {
    key: "EXERCISE_COMPLETIONIST",
    title: "Exercise Completionist 🏆",
    description: "Complete all available exercises",
    icon: "🏆",
    category: "exercise",
    rarity: "LEGENDARY",
    points: 500,
    requirementType: "all_exercises_complete",
    requirementValue: 1,
    isHidden: false,
  },

  // Learning Approach Achievement
  {
    key: "SOLUTION_SEEKER",
    title: "Solution Seeker 📖",
    description: "View solutions to learn different approaches",
    icon: "📖",
    category: "exercise",
    rarity: "COMMON",
    points: 5,
    requirementType: "solution_viewed",
    requirementValue: 5,
    isHidden: false,
  },
];
