#!/bin/bash

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Vibed to Cracked - Deployment Script${NC}"
echo "========================================="

if ! command -v docker >/dev/null 2>&1; then
    echo -e "${RED}Docker is not installed. Install Docker first.${NC}"
    exit 1
fi

if docker compose version >/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE_CMD="docker-compose"
else
    echo -e "${RED}Docker Compose is not available. Install docker compose plugin or docker-compose.${NC}"
    exit 1
fi

prompt_input() {
    local prompt="$1"
    local var_name="$2"
    local default_value="${3:-}"
    local input

    if [ -n "$default_value" ]; then
        read -r -p "$prompt [$default_value]: " input
        input=${input:-$default_value}
    else
        read -r -p "$prompt: " input
    fi

    eval "$var_name=\"$input\""
}

if [ ! -f ".env.production" ]; then
    echo -e "${YELLOW}.env.production not found. Creating it now.${NC}"

    prompt_input "Enter your domain name (example.com)" DOMAIN
    prompt_input "Enter email for ACME certificates" ACME_EMAIL
    prompt_input "Enter PostgreSQL password" POSTGRES_PASSWORD

    echo -e "${YELLOW}Generating NextAuth secret...${NC}"
    NEXTAUTH_SECRET=$(openssl rand -base64 32)

    echo -e "${BLUE}OAuth setup references:${NC}"
    echo "GitHub: https://github.com/settings/applications/new"
    echo "Google: https://console.developers.google.com/"

    prompt_input "Enter GitHub Client ID" GITHUB_ID
    prompt_input "Enter GitHub Client Secret" GITHUB_SECRET
    prompt_input "Enter Google Client ID" GOOGLE_CLIENT_ID
    prompt_input "Enter Google Client Secret" GOOGLE_CLIENT_SECRET
    prompt_input "Enter Stripe Secret Key (optional)" STRIPE_SECRET_KEY ""
    prompt_input "Enter Stripe Webhook Secret (optional)" STRIPE_WEBHOOK_SECRET ""

    cat > .env.production << EOF
# Generated by scripts/deploy.sh
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

POSTGRES_DB=vibed_to_cracked
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/vibed_to_cracked

NEXTAUTH_URL=https://${DOMAIN}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

GITHUB_ID=${GITHUB_ID}
GITHUB_SECRET=${GITHUB_SECRET}

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

EMAIL_FROM=noreply@${DOMAIN}
EOF

    echo -e "${GREEN}Created .env.production${NC}"
fi

echo -e "${BLUE}Building and starting services...${NC}"
$COMPOSE_CMD --env-file .env.production up -d --build

echo -e "${BLUE}Waiting for services to start...${NC}"
sleep 12

echo -e "${BLUE}Running database migrations...${NC}"
$COMPOSE_CMD --env-file .env.production exec -T app npx prisma migrate deploy

echo -e "${BLUE}Running database seed...${NC}"
$COMPOSE_CMD --env-file .env.production exec -T app npx prisma db seed

DOMAIN=$(grep "^DOMAIN=" .env.production | cut -d'=' -f2)

echo -e "${BLUE}Validating Caddy and certificate status...${NC}"
$COMPOSE_CMD --env-file .env.production logs --tail=40 caddy

echo
echo -e "${GREEN}Deployment completed.${NC}"
echo
echo -e "${BLUE}Running services:${NC}"
echo "- Next.js app behind Caddy: https://${DOMAIN}"
echo "- PostgreSQL database"
echo "- Caddy reverse proxy with automatic TLS"
echo
echo -e "${BLUE}Useful commands:${NC}"
echo "- View logs: $COMPOSE_CMD --env-file .env.production logs -f"
echo "- Stop services: $COMPOSE_CMD --env-file .env.production down"
echo "- Update app: $COMPOSE_CMD --env-file .env.production up --build -d app"
echo "- Database backup: $COMPOSE_CMD --env-file .env.production exec -T db pg_dump -U postgres vibed_to_cracked > backup.sql"
echo
echo -e "${YELLOW}Security reminders:${NC}"
echo "- Keep .env.production private"
echo "- Restrict inbound ports to 22/80/443"
echo "- Monitor container logs and disk usage"
