param(
    [string]$Domain,
    [string]$AcmeEmail,
    [switch]$Help
)

$Red = "Red"
$Green = "Green"
$Yellow = "Yellow"
$Blue = "Cyan"

function Write-ColorOutput {
    param($Color, $Message)
    Write-Host $Message -ForegroundColor $Color
}

function Show-Help {
    Write-ColorOutput $Blue "Vibed to Cracked - Windows Deployment Script"
    Write-Host "=================================================="
    Write-Host ""
    Write-Host "Usage: .\deploy.ps1 [-Domain <domain>] [-AcmeEmail <email>] [-Help]"
    Write-Host ""
    Write-Host "Example:"
    Write-Host "  .\deploy.ps1 -Domain 'mysite.com' -AcmeEmail 'admin@mysite.com'"
    Write-Host ""
    exit 0
}

function Get-UserInput {
    param($Prompt, $Default = "")
    if ($Default) {
        $userInput = Read-Host "$Prompt [$Default]"
        if ([string]::IsNullOrWhiteSpace($userInput)) {
            return $Default
        }
        return $userInput
    }
    return (Read-Host $Prompt)
}

if ($Help) {
    Show-Help
}

Write-ColorOutput $Blue "Vibed to Cracked - Deployment Script"
Write-Host "========================================="

try {
    $dockerVersion = docker --version
    Write-ColorOutput $Green "Docker found: $dockerVersion"
}
catch {
    Write-ColorOutput $Red "Docker is not installed or not in PATH."
    exit 1
}

$ComposeBase = @("docker", "compose")
docker compose version *> $null
if ($LASTEXITCODE -ne 0) {
    docker-compose --version *> $null
    if ($LASTEXITCODE -ne 0) {
        Write-ColorOutput $Red "Docker Compose is not available."
        exit 1
    }
    $ComposeBase = @("docker-compose")
}

function Invoke-Compose {
    param(
        [Parameter(ValueFromRemainingArguments = $true)]
        [string[]]$Args
    )

    if ($ComposeBase.Count -eq 2) {
        & $ComposeBase[0] $ComposeBase[1] @Args
    }
    else {
        & $ComposeBase[0] @Args
    }
}

if (-not (Test-Path ".env.production")) {
    Write-ColorOutput $Yellow ".env.production not found. Creating it now."

    if (-not $Domain) {
        $Domain = Get-UserInput "Enter your domain name (example.com)"
    }
    if (-not $AcmeEmail) {
        $AcmeEmail = Get-UserInput "Enter email for ACME certificates"
    }

    $PostgresPassword = Get-UserInput "Enter PostgreSQL password"
    $NextAuthSecret = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(([Guid]::NewGuid().ToString("N") + [Guid]::NewGuid().ToString("N"))))

    Write-ColorOutput $Blue "OAuth setup references:"
    Write-Host "GitHub: https://github.com/settings/applications/new"
    Write-Host "Google: https://console.developers.google.com/"

    $GitHubId = Get-UserInput "Enter GitHub Client ID"
    $GitHubSecret = Get-UserInput "Enter GitHub Client Secret"
    $GoogleClientId = Get-UserInput "Enter Google Client ID"
    $GoogleClientSecret = Get-UserInput "Enter Google Client Secret"
    $StripeSecretKey = Get-UserInput "Enter Stripe Secret Key (optional)" ""
    $StripeWebhookSecret = Get-UserInput "Enter Stripe Webhook Secret (optional)" ""

    $envContent = @"
# Generated by scripts/deploy.ps1
DOMAIN=$Domain
ACME_EMAIL=$AcmeEmail

POSTGRES_DB=vibed_to_cracked
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$PostgresPassword
DATABASE_URL=postgresql://postgres:$PostgresPassword@db:5432/vibed_to_cracked

NEXTAUTH_URL=https://$Domain
NEXTAUTH_SECRET=$NextAuthSecret

GITHUB_ID=$GitHubId
GITHUB_SECRET=$GitHubSecret

GOOGLE_CLIENT_ID=$GoogleClientId
GOOGLE_CLIENT_SECRET=$GoogleClientSecret

STRIPE_SECRET_KEY=$StripeSecretKey
STRIPE_WEBHOOK_SECRET=$StripeWebhookSecret

EMAIL_FROM=noreply@$Domain
"@

    $envContent | Out-File -FilePath ".env.production" -Encoding utf8
    Write-ColorOutput $Green "Created .env.production"
}

$DomainFromEnv = ((Get-Content ".env.production" | Where-Object { $_ -match "^DOMAIN=" }) -replace "^DOMAIN=", "")

Write-ColorOutput $Blue "Building and starting services..."
Invoke-Compose --env-file .env.production up -d --build
if ($LASTEXITCODE -ne 0) {
    Write-ColorOutput $Red "Failed to start services."
    exit 1
}

Write-ColorOutput $Blue "Waiting for services to start..."
Start-Sleep -Seconds 15

Write-ColorOutput $Blue "Running database migrations..."
Invoke-Compose --env-file .env.production exec -T app npx prisma migrate deploy
if ($LASTEXITCODE -ne 0) {
    Write-ColorOutput $Red "Migration failed."
    exit 1
}

Write-ColorOutput $Blue "Running database seed..."
Invoke-Compose --env-file .env.production exec -T app npx prisma db seed

Write-ColorOutput $Blue "Showing recent Caddy logs..."
Invoke-Compose --env-file .env.production logs --tail=40 caddy

Write-Host ""
Write-ColorOutput $Green "Deployment completed."
Write-Host ""
Write-ColorOutput $Blue "Running services:"
Write-Host "- Next.js app behind Caddy: https://$DomainFromEnv"
Write-Host "- PostgreSQL database"
Write-Host "- Caddy reverse proxy with automatic TLS"
Write-Host ""
Write-ColorOutput $Blue "Useful commands:"
Write-Host "- View logs: docker compose --env-file .env.production logs -f"
Write-Host "- Stop services: docker compose --env-file .env.production down"
Write-Host "- Update app: docker compose --env-file .env.production up --build -d app"
Write-Host "- Database backup: docker compose --env-file .env.production exec -T db pg_dump -U postgres vibed_to_cracked > backup.sql"
